# Generated by Django 4.2.8 on 2024-01-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_contents_category_category_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
        migrations.RemoveField(
            model_name='category',
            name='isnew',
        ),
        migrations.AddField(
            model_name='contents',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='image',
            field=models.ImageField(upload_to='contents', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Tür'),
        ),
    ]
