# Generated by Django 4.2.8 on 2024-01-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_remove_category_content_remove_category_isnew_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='category',
        ),
        migrations.AddField(
            model_name='contents',
            name='isnew',
            field=models.BooleanField(default=False, verbose_name='Yeni Eklenmiş'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
