# Generated by Django 4.2.8 on 2024-01-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_contents_ispopular'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='islogin',
            field=models.BooleanField(default=False, verbose_name='Girişli Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='ispopular',
            field=models.BooleanField(default=False, verbose_name='Popüler'),
        ),
    ]
