# Generated by Django 4.2.8 on 2024-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isview',
            field=models.BooleanField(default=True, verbose_name='Görüntüleme'),
        ),
    ]
