# Generated by Django 4.2.8 on 2024-01-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_profile_isview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile', verbose_name='Profil Resmi'),
        ),
    ]
