# Generated by Django 4.2.8 on 2024-01-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='adress',
        ),
    ]
